/*****************************************************************************/
/*                                                                           */
/* FILENAME                                                                  */
/* 	 filtercoefficients.h                                                    */
/*                                                                           */
/* DESCRIPTION                                                               */
/*   contains the FIR filter coefficients                                    */
/*                                                                           */
/* REVISION                                                                  */
/*   Revision: 2.00	                                                         */
/*   Author  : Marc Geilen                                                   */
/*---------------------------------------------------------------------------*/
/*                                                                           */
/* HISTORY                                                                   */
/*   Revision 1.00                                                           */
/*   1st June 2016.                                                          */
/*   Revision 2.00                                                           */
/*   7th June 2019.                                                         */
/*                                                                           */
/*****************************************************************************/

#ifndef FILTERCOEFFICIENTS_H_
#define FILTERCOEFFICIENTS_H_

#include <stdint.h>

/*****************************************************************************/
/* Low Pass Filter Coefficients                                              */
/*****************************************************************************/

// The code below is automatically generated by the Matlab script firdesign.m
// It is an 103th order (length 104) low pass FIR filter with cutoff frequency 500Hz.
// It is for a digital system with a sampling frequency of  44.1kHz.
// The generated filter coefficients are the integer representations of fixed point
// numbers in the representation: Q(16,8).
#define FIR_FILTER_LENGTH 104
#define FIR_FRACTIONAL_BITS 8
const int16_t FIRFilterCoefficients[FIR_FILTER_LENGTH] = {
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 1, 1, 1, 1, 1, 1, 1, 
	1, 2, 2, 2, 2, 3, 3, 3, 
	3, 3, 4, 4, 4, 4, 5, 5, 
	5, 5, 5, 6, 6, 6, 6, 6, 
	6, 6, 6, 6, 6, 6, 6, 6, 
	6, 6, 6, 6, 6, 5, 5, 5, 
	5, 5, 4, 4, 4, 4, 3, 3, 
	3, 3, 3, 2, 2, 2, 2, 1, 
	1, 1, 1, 1, 1, 1, 1, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0
	
};






#endif /*FILTERCOEFFICIENTS_H_*/
